---
title: "Analyse des données de Géovélo"
author: "Document de travail, Nantes Métropole"
date: "26/02/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Enjeux.

# Données

```{r}
library(tidyverse)
library(sf)
library(tmap)
library(tidygeocoder)
library(purrr)
library(stplanr)
library(lwgeom)

freq_file <- "data/stats-fréquentation_des_axes-2021-01-01_2021-12-31.geojson"
amenag_file <- "data/nantes-metropole-2022-02-26-2022-02-26.geojson"
nm_inv_file <- "data/amenagements-cyclables-nantes-metropole-enrichis.geojson"

freq_axes_2021 <- read_sf(freq_file )
amenagements <- read_sf(amenag_file)
nm_inv <- read_sf(nm_inv_file)

# Ajouter cartes générales
```

? Description des données

# Zoom

```{r}
# On part d'un dataframe contenant une adresse
focus_centre <- data.frame(address = "Place René Bouhier, Nantes") %>%
  geocode(address, method = "osm") %>% # on retrouve sa localisation xy
  select(long, lat) %>% # on ne garde que le xy
  as.numeric() %>% # qu'on passe en format numérique attendu par st_point
  st_point() %>% # On le spécifie en point
  st_sfc(crs = "EPSG:4326") 

# On crée une boîte de 500m 
focus <- focus_centre %>% # On repart du centre
  st_buffer(dist = 250) %>% # On crée un cercle de 250m de rayon
  st_make_grid(n = 1)

amenag_focus <- st_intersection(amenagements, focus)
freq_focus <- st_intersection(freq_axes_2021, focus)
inv_focus <- nm_inv %>%
  st_intersection(focus)

amenag_focus_buff10 <- st_buffer(amenag_focus, 10)
inv_focus_b10 <- st_buffer(inv_focus, 10)


# TODO : mettre en forme pour ajouter la fréquentation Géovélo
# TODO : passer en lambert 2 pour une représentation plus propre
tm_shape(inv_focus_b10) + 
  tm_polygons(col = "green", alpha = 0.2) +
tm_shape(inv_focus) + 
  tm_lines() # + 
# tm_shape(freq_focus) + 
#   tm_lines()



```



```{r}
tmap_mode("plot")

sum(duplicated(nm_inv$gid))

step1 <- inv_focus  %>%
  geo_toptail(1) %>% 
  st_transform(27572)

step2 <- step1 %>%
  st_segmentize(units::set_units(1,m))

vor <- step2 %>% 
  st_cast("POINT") %>%
  st_voronoi()

plot(vor)

step2_buf <- step2 %>%
  st_buffer(dist = 20)

test <- st_intersection(step2_buf, vor)

plot(step2_buf)[1,]

plot(vor)

test <- st_length(nm_inv)
length(st_length(nm_inv) > units::set_units(100,m))

min(test)
tm_shape(vor) + 
  tm_borders()
str(vor)
plot(st_cast(step1, "POINT"))

# Essai de Voronoï sur des lignes
inv_focus_id <- inv_focus %>%
  mutate(my_ID = as.character(seq_len(nrow(.)))) %>% 
  st_set_agr("constant")

inv_focus_p <- inv_focus %>%
  st_cast("POINT") %>%
  filter(!duplicated(geometry)) %>% 
  group_by(my_ID) %>% 
  summarise()

voronoi_points_s <- inv_focus_p %>%
  st_voronoi(do.call("c", st_geometry(.))) %>% 
  st_collection_extract() %>% 
  st_set_crs(27572)

voronoi_lines_s <- voronoi_points_s %>%
  st_cast("MULTIPOLYGON", ids = unlist(st_intersects(.,inv_focus_p))) %>% 
  st_union(by_feature = TRUE)
  
inv_focus_b10_nooverlap <- inv_focus_b10 %>%
  st_geometry() %>%
  st_intersection(voronoi_lines_s)

my_solution <- map2(
  .x = st_geometry(st_buffer(inv_focus_id, dist = 10)), 
  .y = voronoi_lines_s, 
  .f = st_intersection
  ) %>% 
  st_sfc()

str(example_points)
vor <- inv_focus %>%
  st_cast("POINT") %>%
  st_union() %>%
  filter(!duplicated(geometry)) %>%
  st_voronoi() %>%
  st_collection_extract(., "POLYGON") %>%
  st_as_sf()

```


```{python}
import geopandas



```






```{r}
# Carte complète : très long à générer
tm_shape(freq_axes_2021) + 
  tm_lines(col = "frequency",
    palette = "YlOrRd",
    style = "fisher", 
    n = 20,
    title.col = "Fréquence des passages enregistrés par Géovélo")
```

```{r}
# Archives

inv_focus_p <- rnet_get_nodes(inv_focus)

vor <- inv_focus %>%
  rnet_get_nodes() %>%
  st_union() %>%
  st_voronoi() %>%
  st_collection_extract(., "POLYGON") %>%
  st_as_sf()
 


inv_focus2 <- inv_focus %>%
  line_breakup(vor)

l_split <- function(l) {
  lwgeom::st_split(l, vor)
  }

test <- inv_focus %>%
  map(l_split)

vor2 <- inv_focus2 %>%
  rnet_get_nodes() %>%
  st_union() %>%
  st_voronoi() %>%
  st_collection_extract(., "POLYGON") %>%
  st_as_sf()


tm_shape(inv_focus_b10) + 
  tm_polygons(col = "green", alpha = 0.2) +
tm_shape(inv_focus) + 
  tm_lines() +
tm_shape(vor2) + 
  tm_borders()


amenag_focus_seg <- 
```

