---
title: "Analyse des données de Géovélo"
author: "Document de travail, Nantes Métropole"
date: "26/02/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Enjeux.

# Données

```{r}
library(tidyverse)
library(sf)
library(tmap)
library(tidygeocoder)
library(purrr)
library(stplanr)
library(lwgeom)

freq_file <- "data/stats-fréquentation_des_axes-2021-01-01_2021-12-31.geojson"
amenag_file <- "data/nantes-metropole-2022-02-26-2022-02-26.geojson"
nm_inv_file <- "data/amenagements-cyclables-nantes-metropole-enrichis.geojson"

freq_axes_2021 <- read_sf(freq_file )
amenagements <- read_sf(amenag_file)
nm_inv <- read_sf(nm_inv_file)

# Ajouter cartes générales
```

? Description des données

# Zoom

```{r}
# On part d'un dataframe contenant une adresse
focus_centre <- data.frame(address = "Place René Bouhier, Nantes") %>%
  geocode(address, method = "osm") %>% # on retrouve sa localisation xy
  select(long, lat) %>% # on ne garde que le xy
  as.numeric() %>% # qu'on passe en format numérique attendu par st_point
  st_point() %>% # On le spécifie en point
  st_sfc(crs = "EPSG:4326") 

# On crée une boîte de 500m 
focus <- focus_centre %>% # On repart du centre
  st_buffer(dist = 250) %>% # On crée un cercle de 250m de rayon
  st_make_grid(n = 1)

amenag_focus <- st_intersection(amenagements, focus)
freq_focus <- st_intersection(freq_axes_2021, focus)
inv_focus <- nm_inv %>%
  st_intersection(focus)

amenag_focus_buff10 <- st_buffer(amenag_focus, 10)
inv_focus_b10 <- st_buffer(inv_focus, 10)


# TODO : mettre en forme pour ajouter la fréquentation Géovélo
# TODO : passer en lambert 2 pour une représentation plus propre
tm_shape(inv_focus_b10) + 
  tm_polygons(col = "green", alpha = 0.2) +
tm_shape(inv_focus) + 
  tm_lines() # + 
# tm_shape(freq_focus) + 
#   tm_lines()



```



```{r}
remotes::install_github("statnmap/cartomisc")
library(cartomisc)
test <- regional_seas(inv_focus)

input2 <- inv_focus %>%
  st_transform(crs = "EPSG:27572")

test <- regional_seas(
  x = input2,
  group = "gid",
  dist = units::set_units(20, m), # buffer distance
  density = units::set_units(1, m) # density of points (the higher, the more precise the region attribution)
)

plot(test)

```

